import type { EvidenceLevel } from "./bd-data";

export type PeopleStructureNode = {
  id: string;
  name: string;
  role: string;
  group: string;
  location?: string;
  parentId?: string;
  relationship: string;
  relationshipConfirmed: boolean;
  evidence: EvidenceLevel;
  status: string;
  dealRole: string;
  sourceTitle: string;
  sourceUrl: string;
};

export type CompanyPeopleStructure = {
  companyId: string;
  asOf: string;
  summary: string;
  sourceTitle: string;
  sourceUrl: string;
  nodes: PeopleStructureNode[];
};

const novartisLeadership =
  "https://www.novartis.com/partnering/partnering-leadership-team";
const novartisStrategy =
  "https://www.novartis.com/about/executive-committee/aharon-ronny-gal-phd";
const novartisOrganization =
  "https://www.novartis.com/news/media-releases/novartis-announces-new-organizational-structure-accelerate-growth-strengthen-pipeline-and-increase-productivity";
const amgenLeadership =
  "https://www.amgen.com/about/leadership/senior-management/rachna-khosla";
const amgenTeam =
  "https://www.amgenbd.com/resource/1610139576000/Brochure_AmgenBD";
const sanofiTeam =
  "https://www.sanofi.com/en/partnering/meet-the-partnering-team";
const astraZenecaTeam =
  "https://www.astrazeneca.com/partnering/our-partnering-teams.html";
const rocheLeadership =
  "https://www.roche.com/about/leadership/boris-zaitra";
const rocheTeam = "https://www.roche.com/contact/partnering";
const pfizerTeam =
  "https://www.pfizer.com/about/partners/research-and-business-development-partnerships";
const pfizerVentures =
  "https://www.pfizer.com/people/leadership/venture-investments/irena_melnikova-phd";
const biogenLeadership = "https://www.biogen.com/company/leadership.html";
const biogenAppointment =
  "https://investors.biogen.com/news-releases/news-release-details/biogen-appoints-adam-feire-head-business-development-and";
const boehringerGlobal =
  "https://www.linkedin.com/posts/boehringer-ingelheim_biotech-bio2025-lifeforward-activity-7340740102383366144-jVZP";
const boehringerForum =
  "https://image.thebell.co.kr/news/img/forum/20260428100610768_2.pdf";

export const companyPeopleStructures: Record<
  string,
  CompanyPeopleStructure
> = {
  novartis: {
    companyId: "novartis",
    asOf: "30 Jul 2026",
    summary:
      "Strategy & Growth oversees business development. The current C&BD leadership page names the functional vertical owners across evaluation, diligence, transactions, finance, legal, alliances and operations.",
    sourceTitle: "Novartis Partnering Leadership Team",
    sourceUrl: novartisLeadership,
    nodes: [
      {
        id: "nvs-vas",
        name: "Vasant (Vas) Narasimhan",
        role: "Chief Executive Officer",
        group: "Executive oversight",
        relationship: "Enterprise leader",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current executive committee",
        dealRole: "Final enterprise governance for material transactions.",
        sourceTitle: "Novartis Executive Committee",
        sourceUrl: novartisOrganization,
      },
      {
        id: "nvs-ronny",
        name: "Aharon (Ronny) Gal",
        role: "Chief Strategy & Growth Officer",
        group: "Executive oversight",
        location: "Basel, CH",
        parentId: "nvs-vas",
        relationship: "Reports to CEO; oversees business development",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Owns end-to-end portfolio strategy, including corporate strategy, R&D portfolio strategy and business development.",
        sourceTitle: "Chief Strategy & Growth Officer profile",
        sourceUrl: novartisStrategy,
      },
      {
        id: "nvs-susanne",
        name: "Susanne Kreutz",
        role: "Global Head Corporate & Business Development",
        group: "C&BD leadership",
        location: "Basel, CH",
        parentId: "nvs-ronny",
        relationship: "Leads C&BD within Strategy & Growth",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Role official; direct reporting line not stated",
        dealRole:
          "Leads the integrated C&BD organization and unified partnering strategy.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-paul",
        name: "Paul Thibodeau",
        role: "Global Head Search & Evaluation",
        group: "Evaluation & diligence",
        location: "Cambridge, US",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Primary scientific entry point for identifying and evaluating external opportunities.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-berthold",
        name: "Berthold Hinzen",
        role: "Global Head, Due Diligence",
        group: "Evaluation & diligence",
        location: "Cambridge, US",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Coordinates the cross-functional evidence review after an opportunity advances.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-tariq",
        name: "Tariq ElRafie",
        role: "Global Head M&A Transactions",
        group: "Transactions",
        location: "Basel, CH",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Owns execution of acquisition and corporate transactions.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-guillaume",
        name: "Guillaume Vignon",
        role: "Global Head BD&L Transactions",
        group: "Transactions",
        location: "Basel, CH",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Leads licensing and collaboration negotiation and deal execution.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-matteo",
        name: "Matteo Ripoli",
        role: "Global Head C&BD Finance",
        group: "Transaction enablement",
        location: "Basel, CH",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Owns valuation, financial analysis and deal economics.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-janet",
        name: "Janet Raimondo",
        role: "Global Head Legal Transactions",
        group: "Transaction enablement",
        location: "East Hanover, US",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Leads transaction legal strategy and contracting.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-arne",
        name: "Arne Wörn",
        role: "Global Head Alliance Management",
        group: "Post-deal",
        location: "Basel, CH",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Owns governance and value delivery after a partnership is signed.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-arun",
        name: "Arun Bisht",
        role: "Head C&BD Excellence and Operations",
        group: "Operations",
        location: "Basel, CH",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Runs operating model, process and organizational excellence.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
      {
        id: "nvs-kirsten",
        name: "Kirsten Shivji",
        role: "Global Business Partner, People & Organization",
        group: "Operations",
        location: "Basel, CH",
        parentId: "nvs-susanne",
        relationship: "C&BD leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Supports organization design and people strategy for C&BD.",
        sourceTitle: "Novartis Partnering Leadership Team",
        sourceUrl: novartisLeadership,
      },
    ],
  },
  amgen: {
    companyId: "amgen",
    asOf: "30 Jul 2026",
    summary:
      "Amgen publicly confirms one enterprise BD leader and describes an integrated organization spanning search, transactions, ventures and alliance management. The functional roster below is retained as a published team snapshot where current direct reporting is not confirmed.",
    sourceTitle: "Amgen Business Development leadership",
    sourceUrl: amgenLeadership,
    nodes: [
      {
        id: "amg-rachna",
        name: "Rachna Khosla",
        role: "Senior Vice President, Business Development",
        group: "Business development leadership",
        location: "Thousand Oaks, US",
        relationship: "Leads all Amgen business development",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Accountable for M&A, licensing, search and evaluation, alliance management and Amgen Ventures.",
        sourceTitle: "Rachna Khosla leadership profile",
        sourceUrl: amgenLeadership,
      },
      {
        id: "amg-jessica",
        name: "Jessica Droge",
        role: "Vice President, External R&D",
        group: "Search & evaluation",
        parentId: "amg-rachna",
        relationship: "Published BD senior leadership team",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Published roster; current reporting needs refresh",
        dealRole: "Scientific scouting and external R&D opportunity evaluation.",
        sourceTitle: "Amgen BD team brochure",
        sourceUrl: amgenTeam,
      },
      {
        id: "amg-janis",
        name: "Janis Naeve",
        role: "Managing Director, Amgen Ventures",
        group: "Ventures",
        parentId: "amg-rachna",
        relationship: "Published BD senior leadership team",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Published roster; current reporting needs refresh",
        dealRole: "Early-stage company investment and strategic venture access.",
        sourceTitle: "Amgen BD team brochure",
        sourceUrl: amgenTeam,
      },
      {
        id: "amg-nate",
        name: "Nate Russell",
        role: "Executive Director, Corporate Strategy",
        group: "Strategy",
        parentId: "amg-rachna",
        relationship: "Published BD senior leadership team",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Published roster; current reporting needs refresh",
        dealRole: "Connects transaction activity with enterprise strategy.",
        sourceTitle: "Amgen BD team brochure",
        sourceUrl: amgenTeam,
      },
      {
        id: "amg-rodrigo",
        name: "Rodrigo Vallejo",
        role: "Executive Director, Transactions Analytics",
        group: "Transactions",
        parentId: "amg-rachna",
        relationship: "Published BD senior leadership team",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Published roster; current reporting needs refresh",
        dealRole: "Supports valuation and quantitative transaction decisions.",
        sourceTitle: "Amgen BD team brochure",
        sourceUrl: amgenTeam,
      },
      {
        id: "amg-chris",
        name: "Chris Urban",
        role: "Vice President, Alliance and Integration Management",
        group: "Post-deal",
        parentId: "amg-rachna",
        relationship: "Published BD senior leadership team",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Published roster; current reporting needs refresh",
        dealRole: "Leads integration and governance after signing.",
        sourceTitle: "Amgen BD team brochure",
        sourceUrl: amgenTeam,
      },
      {
        id: "amg-tara",
        name: "Tara Pabst Marra",
        role: "Director, Strategic Planning and Operations",
        group: "Operations",
        parentId: "amg-rachna",
        relationship: "Published BD senior leadership team",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Published roster; current reporting needs refresh",
        dealRole: "Supports the BD operating rhythm and strategic planning.",
        sourceTitle: "Amgen BD team brochure",
        sourceUrl: amgenTeam,
      },
    ],
  },
  sanofi: {
    companyId: "sanofi",
    asOf: "30 Jul 2026",
    summary:
      "Sanofi publishes the global partnering leader and the functional owners for alliance management, ventures, therapeutic-area BD, out-licensing, digital and Greater China.",
    sourceTitle: "Meet the Sanofi Partnering Team",
    sourceUrl: sanofiTeam,
    nodes: [
      {
        id: "san-monika",
        name: "Monika Vnuk",
        role: "Global Head of Partnering and Business Development",
        group: "Partnering leadership",
        relationship: "Leads global partnering and BD",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole: "Global owner of partnering strategy and business development.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-david",
        name: "David Hering",
        role: "Global Head of Alliance Management",
        group: "Alliance & ventures",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Owns partner governance and post-deal value delivery.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-jason",
        name: "Jason Hafler",
        role: "Managing Director, Sanofi Ventures",
        group: "Alliance & ventures",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Early-stage investment and strategic venture relationships.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-michael",
        name: "Michael Palladinetti",
        role: "Global Head, Immunology & Inflammation BD",
        group: "Therapeutic-area BD",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Primary BD owner for immunology and inflammation.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-brian",
        name: "Brian Bronk",
        role:
          "Global Head BD, Neurology, Oncology, Ophthalmology, Platforms, R&D Transactions & Rare Disease",
        group: "Therapeutic-area BD",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Broad scientific BD owner across multiple priority areas and R&D transactions.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-laurie",
        name: "Laurie Gery",
        role: "Global Head of Business Development, Vaccines",
        group: "Therapeutic-area BD",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Primary BD owner for vaccines opportunities.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-merlin",
        name: "Matthieu Merlin",
        role: "Global Head of Business Development, General Medicines",
        group: "Therapeutic-area BD",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Primary BD owner for General Medicines.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-lebrun",
        name: "Matthieu Lebrun",
        role: "Global Head of Business Development, Out-Licensing",
        group: "Transactions & portfolio",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Owns externalization and out-licensing routes.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-catherine",
        name: "Catherine Blanchette",
        role: "Head of Strategic Digital Partnerships",
        group: "Digital & regional",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Owner for strategic digital partnership opportunities.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
      {
        id: "san-ying",
        name: "Ying Yang",
        role: "Greater China Strategy & Business Development Head",
        group: "Digital & regional",
        parentId: "san-monika",
        relationship: "Partnering leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Key Greater China strategy and BD entry point.",
        sourceTitle: "Meet the Sanofi Partnering Team",
        sourceUrl: sanofiTeam,
      },
    ],
  },
  astrazeneca: {
    companyId: "astrazeneca",
    asOf: "30 Jul 2026",
    summary:
      "AstraZeneca publishes separate partnering routes for BioPharmaceuticals R&D, Corporate Development, International commercial partnering and Pharmaceutical Technology. These are parallel doors rather than one public reporting tree.",
    sourceTitle: "AstraZeneca Partnering Teams",
    sourceUrl: astraZenecaTeam,
    nodes: [
      {
        id: "az-ratan",
        name: "Ratan Bhat",
        role: "VP and Global Head BD&L, BioPharmaceuticals R&D",
        group: "BioPharmaceuticals R&D",
        location: "Gothenburg, SE",
        relationship: "Leads BioPharmaceuticals R&D BD&L",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Global owner for early-stage BioPharmaceuticals R&D partnering.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-nikhil",
        name: "Nikhil Mutyal",
        role: "Executive Director, Head S&E, Respiratory & Immunology",
        group: "BioPharmaceuticals R&D",
        location: "Boston, US",
        parentId: "az-ratan",
        relationship: "BioPharmaceuticals partnering team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Scientific entry point for Respiratory & Immunology.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-josefin",
        name: "Josefin Tevell",
        role: "Executive Director, Head of Transactions, BioPharmaceuticals R&D",
        group: "BioPharmaceuticals R&D",
        location: "Gothenburg, SE",
        parentId: "az-ratan",
        relationship: "BioPharmaceuticals partnering team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Transaction execution for BioPharmaceuticals R&D deals.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-nathan",
        name: "Nathan Styles",
        role: "Executive Director, Head S&E, CVRM",
        group: "BioPharmaceuticals R&D",
        location: "Boston, US",
        parentId: "az-ratan",
        relationship: "BioPharmaceuticals partnering team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Scientific entry point for CVRM.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-susanna",
        name: "Susanna Myhre",
        role: "Head of Academic Partnership, BioPharmaceuticals R&D",
        group: "BioPharmaceuticals R&D",
        location: "Gothenburg, SE",
        parentId: "az-ratan",
        relationship: "BioPharmaceuticals partnering team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Academic collaboration entry point.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-christopher",
        name: "Christopher Church",
        role: "Head of Search & Evaluation, Technology",
        group: "BioPharmaceuticals R&D",
        parentId: "az-ratan",
        relationship: "BioPharmaceuticals partnering team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Technology and platform search and evaluation.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-rodolphe",
        name: "Rodolphe Grepinet",
        role: "SVP, Corporate Development",
        group: "Corporate Development",
        location: "Cambridge, UK",
        relationship: "Leads corporate development route",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole: "Transformational M&A and global new-business opportunities.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-brigitte",
        name: "Brigitte de Lima",
        role: "Senior Director, Corporate Development",
        group: "Corporate Development",
        location: "Cambridge, UK",
        parentId: "az-rodolphe",
        relationship: "Corporate Development team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Corporate development transaction assessment and execution.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-thomas",
        name: "Thomas Debrosse",
        role: "Senior Director, Corporate Development",
        group: "Corporate Development",
        location: "Cambridge, UK",
        parentId: "az-rodolphe",
        relationship: "Corporate Development team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Corporate development transaction assessment and execution.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-richard",
        name: "Richard Yuan",
        role: "Associate Director, Corporate Development",
        group: "Corporate Development",
        location: "Boston, US",
        parentId: "az-rodolphe",
        relationship: "Corporate Development team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "US corporate development entry point.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-bing",
        name: "Bing Chen",
        role: "VP, International Business Development and Venture Fund",
        group: "International & China",
        location: "Shanghai, CN",
        relationship: "Leads International BD and Venture Fund route",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole: "China and international commercial partnering entry point.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
      {
        id: "az-peter",
        name: "Peter Schell",
        role: "Senior Director, Business Development PT&D",
        group: "Pharmaceutical Technology",
        location: "Gothenburg, SE",
        relationship: "Pharmaceutical Technology partnering lead",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Entry point for delivery, devices, manufacturing and pharmaceutical technology partnerships.",
        sourceTitle: "AstraZeneca Partnering Teams",
        sourceUrl: astraZenecaTeam,
      },
    ],
  },
  roche: {
    companyId: "roche",
    asOf: "30 Jul 2026",
    summary:
      "Roche Corporate Business Development is led by Boris Zaïtra, who reports to the Group CEO. The public partnering page then exposes therapeutic, technology, alliance-management and regional owners.",
    sourceTitle: "Roche Pharma Partnering Contacts",
    sourceUrl: rocheTeam,
    nodes: [
      {
        id: "roc-thomas",
        name: "Thomas Schinecker",
        role: "Group Chief Executive Officer",
        group: "Executive oversight",
        relationship: "Enterprise leader",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole: "Executive oversight for Corporate Business Development.",
        sourceTitle: "Roche leadership",
        sourceUrl: rocheLeadership,
      },
      {
        id: "roc-boris",
        name: "Boris Zaïtra",
        role: "Head of Corporate Business Development",
        group: "Executive oversight",
        location: "Basel, CH",
        parentId: "roc-thomas",
        relationship: "Reports to Group CEO",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Leads the organization combining Pharma Partnering and Group Business Development.",
        sourceTitle: "Boris Zaïtra leadership profile",
        sourceUrl: rocheLeadership,
      },
      {
        id: "roc-enza",
        name: "Enza Di Modugno",
        role:
          "Global Head, CRM, Immunology and Infectious Diseases",
        group: "Therapeutic-area partnering",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current role official; direct reporting not stated",
        dealRole: "Global partnering owner across CRM, immunology and ID.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-jean",
        name: "Jean-Eric Charoin",
        role: "Global Head S&E, CRM, Immunology and Infectious Diseases",
        group: "Search & evaluation",
        location: "Basel, CH",
        parentId: "roc-enza",
        relationship: "Area Search & Evaluation lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Scientific evaluation owner for the combined disease areas.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-qiusong",
        name: "Qiusong Tang",
        role: "S&E Lead, CRM, Immunology and Infectious Diseases",
        group: "Search & evaluation",
        location: "South San Francisco, US",
        parentId: "roc-enza",
        relationship: "Area Search & Evaluation lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "US scientific evaluation entry point for these areas.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-gregg",
        name: "Gregg Talbert",
        role: "Global Head Digital & Data",
        group: "Digital & technology",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global owner for digital and data partnering.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-michael",
        name: "Michael Scherer",
        role: "Search & Evaluation Lead, Digital and Data",
        group: "Digital & technology",
        location: "South San Francisco, US",
        parentId: "roc-gregg",
        relationship: "Digital & Data S&E lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Scientific and technical evaluation for digital opportunities.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-isaac",
        name: "Isaac Veinbergs",
        role: "Global Head Neuroscience, Ophthalmology and Rare Disease",
        group: "Therapeutic-area partnering",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global partnering owner for neuroscience and related areas.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-rose",
        name: "Rose Damestani",
        role: "S&E Lead, Neuroscience, Ophthalmology and Rare Disease",
        group: "Search & evaluation",
        location: "South San Francisco, US",
        parentId: "roc-isaac",
        relationship: "Area Search & Evaluation lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Scientific evaluation for neuroscience and related areas.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-patrick",
        name: "Patrick Schleck",
        role: "Global Head Oncology & Haematology",
        group: "Therapeutic-area partnering",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global partnering owner for oncology and haematology.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-robert",
        name: "Robert Wild",
        role: "Global Head S&E, Oncology & Haematology",
        group: "Search & evaluation",
        location: "South San Francisco, US",
        parentId: "roc-patrick",
        relationship: "Area Search & Evaluation lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global scientific evaluation for oncology and haematology.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-zineb",
        name: "Zineb El Fajoui",
        role: "S&E Lead, Oncology & Haematology",
        group: "Search & evaluation",
        location: "Basel, CH",
        parentId: "roc-patrick",
        relationship: "Area Search & Evaluation lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Basel scientific evaluation entry point for oncology.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-barbara",
        name: "Barbara Lueckel",
        role: "Global Head Research Technologies",
        group: "Digital & technology",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global partnering owner for research technologies.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-tomas",
        name: "Tomas Hejhal",
        role: "S&E Lead, Research Technologies",
        group: "Digital & technology",
        location: "Basel, CH",
        parentId: "roc-barbara",
        relationship: "Research Technologies S&E lead",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Scientific evaluation for research technology opportunities.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-matthias",
        name: "Matthias Rueth",
        role: "Global Head of Alliance & Asset Management",
        group: "Alliance & asset management",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global owner for partner governance and asset management.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-ingo",
        name: "Ingo Stiller",
        role: "Head Alliance Management + Chugai",
        group: "Alliance & asset management",
        location: "Basel, CH",
        parentId: "roc-matthias",
        relationship: "Alliance & Asset Management team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Alliance governance, including Chugai relationships.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-oliver",
        name: "Oliver Froescheis",
        role: "Head of Asset Management",
        group: "Alliance & asset management",
        location: "Basel, CH",
        parentId: "roc-matthias",
        relationship: "Alliance & Asset Management team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Portfolio and partnered-asset management.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-beth",
        name: "Beth Odeh-Frikert",
        role: "Head Alliance & Asset Management",
        group: "Alliance & asset management",
        location: "South San Francisco, US",
        parentId: "roc-matthias",
        relationship: "Alliance & Asset Management team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "US alliance and asset-management entry point.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-harm",
        name: "Harm-Jan Borgeld",
        role: "Global Head Asia Corporate Business Development",
        group: "Asia Corporate BD",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Global owner for Asia corporate business development.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-wenjia",
        name: "Wenjia Li",
        role: "Associate Director BD, China, Taiwan & Singapore",
        group: "Asia Corporate BD",
        parentId: "roc-harm",
        relationship: "Asia Corporate BD team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Greater China and Singapore corporate BD entry point.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-takumi",
        name: "Takumi Matsumoto",
        role: "Director Business Development, Japan",
        group: "Asia Corporate BD",
        parentId: "roc-harm",
        relationship: "Asia Corporate BD team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Japan corporate BD entry point.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-hailey",
        name: "Hailey Jung",
        role: "Business Development Project Leader, Korea",
        group: "Asia Corporate BD",
        parentId: "roc-harm",
        relationship: "Asia Corporate BD team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "Korea corporate BD entry point.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
      {
        id: "roc-anna",
        name: "Anna Williamson",
        role: "Executive Director, UK & Global",
        group: "Regional Corporate BD",
        parentId: "roc-boris",
        relationship: "Corporate BD contact team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official",
        dealRole: "UK and global corporate BD entry point.",
        sourceTitle: "Roche Pharma Partnering Contacts",
        sourceUrl: rocheTeam,
      },
    ],
  },
  pfizer: {
    companyId: "pfizer",
    asOf: "30 Jul 2026",
    summary:
      "Pfizer's public partnering page exposes therapeutic-area contact points rather than a reporting tree. The map therefore shows functional ownership without inventing a global reporting line.",
    sourceTitle: "Pfizer Research and Business Development Partnerships",
    sourceUrl: pfizerTeam,
    nodes: [
      {
        id: "pfi-steve",
        name: "Steve Bartz",
        role: "Biotechnology Partnerships Contact — Oncology",
        group: "Biotechnology partnerships",
        relationship: "Oncology contact point",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official contact",
        dealRole: "Public entry point for oncology biotechnology partnerships.",
        sourceTitle: "Pfizer Research and BD Partnerships",
        sourceUrl: pfizerTeam,
      },
      {
        id: "pfi-lauren",
        name: "Lauren Shearman",
        role: "Biotechnology Partnerships Contact — Metabolic/Obesity",
        group: "Biotechnology partnerships",
        relationship: "Metabolic/Obesity contact point",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official contact",
        dealRole: "Public entry point for metabolic and obesity partnerships.",
        sourceTitle: "Pfizer Research and BD Partnerships",
        sourceUrl: pfizerTeam,
      },
      {
        id: "pfi-allison",
        name: "Allison Kean",
        role: "Biotechnology Partnerships Contact — Cardiovascular",
        group: "Biotechnology partnerships",
        relationship: "Cardiovascular contact point",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official contact",
        dealRole: "Public entry point for cardiovascular partnerships.",
        sourceTitle: "Pfizer Research and BD Partnerships",
        sourceUrl: pfizerTeam,
      },
      {
        id: "pfi-joel",
        name: "Joel Klappenbach",
        role: "Biotechnology Partnerships Contact — I&I",
        group: "Biotechnology partnerships",
        relationship: "Inflammation & Immunology contact point",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official contact",
        dealRole: "Public entry point for inflammation and immunology.",
        sourceTitle: "Pfizer Research and BD Partnerships",
        sourceUrl: pfizerTeam,
      },
      {
        id: "pfi-giuseppe",
        name: "Giuseppe Lofano",
        role: "Biotechnology Partnerships Contact — Vaccines",
        group: "Biotechnology partnerships",
        relationship: "Vaccines contact point",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official contact",
        dealRole: "Public entry point for vaccines partnerships.",
        sourceTitle: "Pfizer Research and BD Partnerships",
        sourceUrl: pfizerTeam,
      },
      {
        id: "pfi-katrina",
        name: "Katrina Loomis",
        role: "Academic & Public Partnerships Contact",
        group: "Academic & public partnerships",
        relationship: "Academic and public partnership contact point",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official contact",
        dealRole: "Public entry point for academic and public collaborations.",
        sourceTitle: "Pfizer Research and BD Partnerships",
        sourceUrl: pfizerTeam,
      },
      {
        id: "pfi-irena",
        name: "Irena Melnikova",
        role: "Executive Director, Worldwide BD / Partner, Pfizer Ventures",
        group: "Pfizer Ventures",
        relationship: "Venture investment leadership",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current official",
        dealRole:
          "Identifies, evaluates and manages strategic equity investments.",
        sourceTitle: "Irena Melnikova leadership profile",
        sourceUrl: pfizerVentures,
      },
    ],
  },
  biogen: {
    companyId: "biogen",
    asOf: "30 Jul 2026",
    summary:
      "Biogen publicly confirms the corporate-development leader and an explicit reporting line from the Head of Business Development and External Innovation.",
    sourceTitle: "Biogen leadership and BD appointment",
    sourceUrl: biogenAppointment,
    nodes: [
      {
        id: "bio-chris",
        name: "Christopher A. Viehbacher",
        role: "President and Chief Executive Officer",
        group: "Executive oversight",
        relationship: "Enterprise leader",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Current leadership team",
        dealRole: "Enterprise oversight of portfolio and growth strategy.",
        sourceTitle: "Biogen Leadership",
        sourceUrl: biogenLeadership,
      },
      {
        id: "bio-keeney",
        name: "Adam Keeney",
        role: "Head of Corporate Development",
        group: "Corporate Development",
        parentId: "bio-chris",
        relationship: "Executive leadership team",
        relationshipConfirmed: false,
        evidence: "A",
        status: "Current official; CEO reporting not stated",
        dealRole: "Leads corporate development and external growth strategy.",
        sourceTitle: "Biogen Leadership",
        sourceUrl: biogenLeadership,
      },
      {
        id: "bio-feire",
        name: "Adam Feire",
        role: "Head of Business Development and External Innovation",
        group: "Business Development",
        location: "Cambridge, US",
        parentId: "bio-keeney",
        relationship: "Reports to Adam Keeney",
        relationshipConfirmed: true,
        evidence: "A",
        status: "Explicit reporting line announced 9 Jan 2025",
        dealRole:
          "Leads search and evaluation plus BD transactions, including M&A.",
        sourceTitle: "Biogen appoints Adam Feire",
        sourceUrl: biogenAppointment,
      },
    ],
  },
  boehringer: {
    companyId: "boehringer",
    asOf: "30 Jul 2026",
    summary:
      "Boehringer publicly identifies the global Human Pharma BD&L leader. A 2026 company presentation also identifies a scientific external-innovation leader, but does not state a direct reporting line between them.",
    sourceTitle: "Boehringer Ingelheim global BD&L",
    sourceUrl: boehringerGlobal,
    nodes: [
      {
        id: "boe-scott",
        name: "Scott DeWire",
        role: "Corporate SVP and Head of Global Business Development & Licensing",
        group: "Global BD&L",
        relationship: "Leads global Business Development & Licensing",
        relationshipConfirmed: true,
        evidence: "B",
        status: "Company social channel confirmation",
        dealRole:
          "Global owner for external innovation access and licensing strategy.",
        sourceTitle: "Boehringer Ingelheim BIO partnering update",
        sourceUrl: boehringerGlobal,
      },
      {
        id: "boe-lena",
        name: "Lena Iwai",
        role: "Eye Health & Research Beyond Borders",
        group: "External innovation",
        parentId: "boe-scott",
        relationship: "Adjacent external-innovation leader",
        relationshipConfirmed: false,
        evidence: "B",
        status: "Role shown in 2026 company presentation; reporting not stated",
        dealRole:
          "Connects emerging science, Grass Roots BD&L and research-beyond-borders programs.",
        sourceTitle: "Working Together to Innovate for Patients",
        sourceUrl: boehringerForum,
      },
    ],
  },
};

